# Generated by Django 2.2.7 on 2019-12-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, verbose_name='Kategori')),
                ('categoryExp', models.CharField(max_length=100, verbose_name='Aciklama')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('productCaption', models.CharField(max_length=100, verbose_name='Başlık')),
                ('productContain', models.CharField(max_length=200, verbose_name='Ürün açıklaması')),
                ('image1', models.ImageField(upload_to='', verbose_name='Urun Resmi 1')),
                ('image2', models.ImageField(upload_to='', verbose_name='Urun Resmi 2')),
                ('image3', models.ImageField(upload_to='', verbose_name='Urun Resmi 3')),
                ('image4', models.ImageField(upload_to='', verbose_name='Urun Resmi 4')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2category', to='model.category', verbose_name='Cat')),
            ],
        ),
        migrations.CreateModel(
            name='newArrivals',
            fields=[
                ('newAr_id', models.AutoField(primary_key=True, serialize=False)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urun1urun', to='model.products', verbose_name='Ürün')),
            ],
        ),
    ]
