# Generated by Django 2.2.7 on 2019-12-05 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Kateori Menü Resmi'),
            preserve_default=False,
        ),
    ]
