# Generated by Django 2.2.7 on 2019-12-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_category_catimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='Hakkımızda image')),
                ('text1', models.CharField(max_length=1000, verbose_name='Hakkımızda yazı 1 ')),
                ('text2', models.CharField(max_length=1000, verbose_name='Hakkımızda yazı 2 ')),
                ('text3', models.CharField(max_length=1000, verbose_name='Hakkımızda yazı 3 ')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='İletişim image')),
                ('text1', models.CharField(max_length=1000, verbose_name='İletişim yazı 1')),
                ('address', models.CharField(max_length=1000, verbose_name='Adresimiz')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon numaramız')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail adresimiz')),
                ('coordinatelat', models.CharField(max_length=40, verbose_name='Koordinatlarımız - Lat ')),
                ('coordinatelong', models.CharField(max_length=40, verbose_name='Koordinatlarımız - Long')),
            ],
        ),
    ]
